# Generated by Django 5.0.7 on 2024-08-23 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(limit_choices_to={'is_manager': True, 'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chapter',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='course.course'),
        ),
        migrations.AddField(
            model_name='module',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='course.chapter'),
        ),
        migrations.AddField(
            model_name='quizz',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='course.module'),
        ),
        migrations.AddField(
            model_name='resources',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='course.module'),
        ),
        migrations.AddField(
            model_name='subscriptionduration',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='durations', to='course.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='module',
            name='video',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='module', to='course.video'),
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('course', 'order'), ('course', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='module',
            unique_together={('chapter', 'order'), ('chapter', 'video')},
        ),
    ]
