# Generated by Django 5.0.7 on 2024-08-23 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizz',
            old_name='answer',
            new_name='answers',
        ),
    ]
