# Generated by Django 5.0.7 on 2024-08-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Answer',
            new_name='UserQuestionnaireResponse',
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='answer_choice',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/media/dragon.jpg', upload_to='users'),
        ),
    ]
